### ISSUE TITLE
Vale's Feedback

### ISSUE THREAD

**Issue by valeschmied** [OpenManifest/openmanifest#47]
1. can't seem to be able to add google address without location turned on - I live in Innisfail and wanna add tully dz address on settings... it won't let me.
2. on setting up my profile... the setup wizard was a bit weird when it came to add canopy size and all... i had to go back in after the wizard to adjust info like exit weight and canopy size... 
3. the inspection sheet won't let me tick boxes
4. hop and pop and height jumps for us is same price but will change config of min load... 6 hp or 10 height to send it... thought it would be tricky to manage
5. type of jumps I haven't really seen how it would work... would we have to load of different type of jumps and then tick as we manifest?
6. permission for user may want to allow a few ticks per user... some of us can be funjump, coach, dzso , lm, gca but at different time - it seemed if I changed mine from owner to gca... i would loose other permission...

**Comment by Amnesthesia** [comment]
hi @valeschmied 

> can't seem to be able to add google address without location turned on - I live in Innisfail and wanna add tully dz address on settings... it won't let me.

This is an oversight, I can add a box to manually enter an address :)

> on setting up my profile... the setup wizard was a bit weird when it came to add canopy size and all... i had to go back in after the wizard to adjust info like exit weight and canopy size...

I think this is an Android bug, where on some Android devices depending on their screen size don't let you scroll down on the wizards. I will fix this today

> the inspection sheet won't let me tick boxes
This is intentional, and it's because you don't have **Rig Inspector** permissions. As an owner, you can grant yourself those permissions on your profile. I already have a task on clarifying this on that screen, but I will make this more clear 

> hop and pop and height jumps for us is same price but will change config of min load... 6 hp or 10 height to send it... thought it would be tricky to manage
That makes sense. At the moment, the minimum slots isn't really used and you can still send a load with less, but it's up to you. Would it make sense to set a total ticket value instead of slot value?

> type of jumps I haven't really seen how it would work... would we have to load of different type of jumps and then tick as we manifest?
Jump types are linked to licenses, so you can only select jump types that your license allows, and if multiple people manifest they can only select jump types allowed by the person with the lowest license rating

> permission for user may want to allow a few ticks per user... some of us can be funjump, coach, dzso , lm, gca but at different time - it seemed if I changed mine from owner to gca... i would loose other permission...

DZSO, GCA, Rig Inspector and Pilot are special permissions that anybody can have on top of whatever role they have. They are visible on the Profile screen as little chips under your name. You can tap those to grant or revoke those permissions for other users

Otherwise roles are usually inheritance based, so a Coach would have all permissions of a Fun jumper plus maybe a few more, and so on — if you're a coach, you would just have the Coach role and that would also give you Fun Jumper permissions, but you can still have GCA and DZSO

**Comment by Amnesthesia** [comment]
Hey @valeschmied , I think I've fixed most of these issues :) Should be updated
